### ISSUE TITLE
Add text extractor 

### ISSUE THREAD

**Issue by adishjain** [adishjain/GoogleResultScrapper#1]
**Elements to be traced within a specific page**
- [x] span
- [x] strong
- [x] b
- [x] pre
- [x] article
- [x] summary
  _Expected language: JAVA_

**Comment by AggarwalAditya** [comment]
You want to extract the main content from each url ?

**Comment by adishjain** [comment]
Yes that's the idea. You think you can help?

**Comment by jainaman224** [comment]
Please see this https://jsoup.org/cookbook/extracting-data/example-list-links.
I think you want something like Doc.select();

**Comment by adishjain** [comment]
@jainaman224 We're already implementing it.

**Comment by AggarwalAditya** [comment]
Yes I can help ... Please reopen the issue.

**Comment by AggarwalAditya** [comment]
Is it okay if I do it using Python?

**Comment by adishjain** [comment]
Yeah sure! No problem in that. 
Just make sure you create a new scrawler as mentioned in the other issue.
