### ISSUE TITLE
Text Extractor in Python

### ISSUE THREAD

**Issue by adishjain** [adishjain/GoogleResultScrapper#5]
**Scrapper**
Creating a scrapper at first to scrape the first 10 "Google Search Results"

**Comment by iamprakashom** [comment]
I am on it :smile:

**Comment by adishjain** [comment]
Thank You! Please proceed.

**Comment by AggarwalAditya** [comment]
@adishjain  Google results cannot be scrapped , instead Custom Search API is used. The free version of the API allows 100 hits per day.  I have already integrated the API in python for one of your issues (PR has been sent) . Can I help you with this one as well ?

**Comment by jainaman224** [comment]
@AggarwalAditya Please let me try it once.

**Comment by AggarwalAditya** [comment]
Sure @jainaman24.
